token=''
appid=''
aeskey=''
openai_key='sk-'
azure_openai_key=''
api_type='azure'
api_version='2022-12-01' #this may change in the future
api_base='https://yourapi.openai.azure.com/' #your endpoint should look like the following https://YOUR_RESOURCE_NAME.openai.azure.com/  #for openai API: https://api.openai.com/v1/completions
deployment_name='text-davinci-003' #This will correspond to the custom name you chose for your deployment when you deployed a model.